version: '2'
services:
  java11:
    build:
      context: .
      args:
        JDK_VER: 19-jdk-alpine
    image: haohonglong/java:11
    container_name: java11
    hostname: java11
    restart: always
    ports:
      - "8081:8080"
      - "5006:5005"
    working_dir: /www
    volumes:
      - ${SOURCE_DIR}:/www
      - ${MAVEN_CONF}/settings.xml:/root/.m2/settings.xml:ro
      - ${MAVEN_REPOSITORY}:/root/.m2/repository
    environment:
      - TZ=$TZ
    networks:
      - default
    
  maven:
    image: haohonglong/maven:1.0.1
    container_name: maven
    hostname: maven
    restart: always
    ports:
      - "8080:8080"
      - "5005:5005"
    working_dir: /www
    extra_hosts:
      - "blog.admin:$HOST_IP"
    volumes:
      - ${SOURCE_DIR}:/www
      - ${MAVEN_CONF}/settings.xml:/root/.m2/settings.xml:ro
      - ${MAVEN_REPOSITORY}:/root/.m2/repository
    environment:
      - TZ=$TZ
      - HOSTIP=$HOST_IP
    networks:
      - default

  oraclejdk8:
    image: haohonglong/oraclejdk8:1.0.2
    container_name: oraclejdk8
    hostname: oraclejdk8
    ports:
      - "8080:8080"
      - "8088:8088"
      - "5006:5005"
    working_dir: /opt/apache-tomcat-9.0.29/webapps
    volumes:
      - ${SOURCE_DIR}:/www
      - ${TOMCAT}/tmall:/opt/apache-tomcat-9.0.29
      - ${MAVEN_CONF}/settings.xml:/root/.m2/settings.xml:ro
      - ${MAVEN_REPOSITORY}:/root/.m2/repository
    environment:
      - TZ=$TZ
    networks:
      - default

  tomcat:
    image: tomcat:9.0
    container_name: tomcat
    hostname: tomcat
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - "${TOMCAT}:/usr/local/tomcat"
    networks:
      - default

networks:
  default:
    driver: bridge


